services:
  app:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    image: gv
    container_name: gv-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - app_network
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    container_name: gv-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./src/mysql:/docker-entrypoint-initdb.d
    networks:
      - app_network
  nginx:
    image: nginx:alpine
    working_dir: /var/www
    container_name: gv-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80" #bind port 8080 to port 80 in the container
    volumes:
      - ./src:/var/www
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  dbdata:
    driver: local